server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/petadoption
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.MySQLDialect
