server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/petadoption
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true


