# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: us-south1-docker.pkg.dev/possible-cocoa-438319-m0/dogpile-repo/react-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: react-frontend
  ports:
    - name: http # Add a unique name to the port
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: metrics # Add a name for the second port
      protocol: TCP
      port: 8080
      targetPort: 8080
