apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: us-south1-docker.pkg.dev/possible-cocoa-438319-m0/dogpile-repo/spring-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: FILE_UPLOAD_DIR
              value: "/tmp/uploads"
          volumeMounts:
            - mountPath: /tmp/uploads
              name: uploads-volume  # Name must match the volume defined below
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc  # This should match the PVC name exactly
