apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  selector:
    app: spring-backend  # Must match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80             # Port exposed externally
      targetPort: 8080      # Port the backend listens on
  type: LoadBalancer       # Change this to NodePort if you're not using GCP or cloud provider
