name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create credentials file from secret
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "possible-cocoa-438319-m0"
          service_account_key_file: /tmp/key.json
          export_default_credentials: true
          
      - name: Verify Authentication 
        run: |
          gcloud auth list
          gcloud config list

      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth configure-docker us-south1-docker.pkg.dev
          
      - name: Build and push backend image
        run: |
          docker build --no-cache -f "docker/pet-adoption-api.Dockerfile" -t us-south1-docker.pkg.dev/possible-cocoa-438319-m0/dogpile-repo/spring-backend:latest .
          docker push us-south1-docker.pkg.dev/possible-cocoa-438319-m0/dogpile-repo/spring-backend:latest

      - name: Restart backend pods
        run: |
          kubectl delete pods -l app=spring-backend --wait

      - name: Build and push frontend image
        run: |
          docker build --no-cache -f "docker/pet-adoption-frontend.Dockerfile" -t us-south1-docker.pkg.dev/possible-cocoa-438319-m0/dogpile-repo/react-frontend:latest .
          docker push us-south1-docker.pkg.dev/possible-cocoa-438319-m0/dogpile-repo/react-frontend:latest

      - name: Restart frontend pods
        run: |
          kubectl delete pods -l app=react-frontend --wait
