name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Write Service Account Key to File
        run: |
          cat <<EOF > /tmp/key.json
          ${{ secrets.GCP_SA_KEY }}
          EOF

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker "us-south1-docker.pkg.dev"

      - name: Authenticate with GKE Cluster
        run: |
          gcloud container clusters get-credentials dogpile-cluster-1 --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify Kubernetes Connection
        run: |
          kubectl get pods --all-namespaces

      - name: Build and Push Backend Image
        run: |
          docker build --no-cache -f "docker/pet-adoption-api.Dockerfile" -t ${{ secrets.BACKEND_IMAGE }}:latest .
          docker push ${{ secrets.BACKEND_IMAGE }}:latest

      - name: Restart Backend Pods
        run: |
          kubectl delete pods -l app=spring-backend --wait

      - name: Build and Push Frontend Image
        run: |
          docker build --no-cache -f "docker/pet-adoption-frontend.Dockerfile" -t ${{ secrets.FRONTEND_IMAGE }}:latest .
          docker push ${{ secrets.FRONTEND_IMAGE }}:latest

      - name: Restart Frontend Pods
        run: |
          kubectl delete pods -l app=react-frontend --wait
