name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials <cluster-name> \
            --zone <zone> --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify Cluster Connection
        run: |
          kubectl get nodes

      - name: Start Docker service
        run: sudo service docker start

      - name: Build and Push Backend Image
        run: |
          docker build --no-cache -f "docker/pet-adoption-api.Dockerfile" -t ${{ secrets.BACKEND_IMAGE }}:latest .
          docker push ${{ secrets.BACKEND_IMAGE }}:latest

      - name: Restart Backend Pods
        run: |
          kubectl rollout restart deployment/spring-backend

      - name: Build and Push Frontend Image
        run: |
          docker build --no-cache -f "docker/pet-adoption-frontend.Dockerfile" -t ${{ secrets.FRONTEND_IMAGE }}:latest .
          docker push ${{ secrets.FRONTEND_IMAGE }}:latest

      - name: Restart Frontend Pods
        run: |
          kubectl rollout restart deployment/react-frontend
